package br.com.view;
import br.com.controller.CelularController;
import br.com.modelo.negocio.Celular;
import br.com.validators.Validadores;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Rosicléia Frasson
 */
public class InserirCelularGui extends javax.swing.JFrame {

    CelularTableModel model;

    /**
     * Creates new form InserirCelularGui
     */
    public InserirCelularGui(CelularTableModel mtb) {
        initComponents();
        model = mtb;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txDescricao = new javax.swing.JTextField();
        botaoLimpar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txObservacoes = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txPreco = new javax.swing.JTextField();

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("YYYY"))));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Marca");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("Inserir Celularl");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(57, 11, 69, 14);

        jLabel2.setText("Descrição.:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 46, 80, 14);
        jPanel1.add(txDescricao);
        txDescricao.setBounds(108, 43, 70, 20);

        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rosicleiafrasson/view/imagens/limpar.png"))); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });
        jPanel1.add(botaoLimpar);
        botaoLimpar.setBounds(150, 340, 110, 23);

        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rosicleiafrasson/view/imagens/salvar.png"))); // NOI18N
        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoSalvar);
        botaoSalvar.setBounds(279, 340, 120, 23);

        jLabel5.setText("Observações.:   ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 90, 100, 14);

        txObservacoes.setColumns(20);
        txObservacoes.setRows(5);
        jScrollPane1.setViewportView(txObservacoes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 90, 294, 74);

        jLabel6.setText("Preço.:  ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 190, 80, 14);
        jPanel1.add(txPreco);
        txPreco.setBounds(110, 190, 80, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        Celular c = new Celular();


       

          
          
           
           c.setPreco((Float.parseFloat(txPreco.getText())));
           CelularController cc = new CelularController();
            if(cc.cadastrar(c)){
            model.addCelular(pesquisar(c.getDescricao()));
            }
            dispose();
        
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private Celular pesquisar ( String descricao){
        CelularController cc = new CelularController();
        return cc.listarCelularByNome(descricao)
    }
    
    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        txDescricao.setText("");
        
        txPreco.setText("");
        
    }//GEN-LAST:event_botaoLimparActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txDescricao;
    private javax.swing.JTextArea txObservacoes;
    private javax.swing.JTextField txPreco;
    // End of variables declaration//GEN-END:variables

   
}
